### ISSUE TITLE
Deleted items are still visible in Unique scan

### ISSUE THREAD

**Issue by GuiGou12358** [UniqueNetwork/unique-scan-backend#2]
Deleted items are still visible in Unique scan.

By example, for the collection https://uniquescan.io/QUARTZ/collections/17
The second NFT is listed but it was deleted.

It would be better to not display deleted items or mark them as 'deleted' in the UI

**Comment by sswebcoder** [comment]
Thank you for Issue, this problem was fixed in our last release in current scanner.

https://github.com/UniqueNetwork/unique-explorer-api/releases/tag/v1.6.2
